quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.rest-client.area-api.url=http://100.26.55.42:80/
quarkus.rest-client.area-api.scope=javax.inject.Singleton #

quarkus.swagger-ui.enable=true
quarkus.swagger-ui.always-include=true

quarkus.http.test-port=0
quarkus.http.test-ssl-port=0

quarkus.datasource.db-kind=h2
quarkus.hibernate-orm.dialect=org.hibernate.dialect.H2Dialect
quarkus.hibernate-orm.log.sql=true

quarkus.datasource.jdbc.url=jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
quarkus.datasource.jdbc.driver=org.h2.Driver
quarkus.datasource.username=sa
quarkus.datasource.password=

quarkus.hibernate-orm.sql-load-script=import.sql

quarkus.smallrye-openapi.path=/api/openapi
quarkus.swagger-ui.path=/q/swagger-ui\